name: Build and Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: "--win"
          - os: macos-latest
            target: "--mac dmg"
          - os: ubuntu-latest
            target: "--linux deb AppImage"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # Устанавливаем недостающую утилиту bsdtar для сборки pacman
      - name: Install Linux tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libarchive-tools

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build and Publish to Release
        run: npx electron-builder ${{ matrix.target }} --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
